/**
 * officerId generation for Manual Personnel Entry (Phase XX — Admin Only).
 *
 * Every existing Officer.officerId is derived by the import pipeline from a
 * Google Drive source file (region/filename — see lib/import/validation.ts),
 * so it never starts with "manual/". A hand-created officer has no source
 * file, so this generates a `manual/{uuid}` id instead — guaranteed unique,
 * cannot collide with any Drive-derived id, and is immediately recognizable
 * as manually entered from the id alone (in addition to the `source` column).
 *
 * Pure — no I/O, no database.
 */

import { randomUUID } from "crypto";

export const MANUAL_ENTRY_ID_PREFIX = "manual/";

export function generateManualOfficerId(): string {
  return `${MANUAL_ENTRY_ID_PREFIX}${randomUUID()}`;
}

/** True when `officerId` was generated by generateManualOfficerId (i.e. this row's source is manual entry, by id shape alone). */
export function isManualOfficerId(officerId: string): boolean {
  return officerId.startsWith(MANUAL_ENTRY_ID_PREFIX);
}
