/**
 * Root loading UI (PWA splash/loading section — additive).
 *
 * Next.js renders this automatically during a route-level Suspense
 * boundary (e.g. a slow server navigation) — it is NOT the OS-level PWA
 * launch splash (that one is generated by the browser itself from
 * manifest.json's background_color/icons and can't be custom-styled), but
 * it gives the app a consistent, on-brand loading frame for in-app
 * navigations too, using the same logo and theme background so there's no
 * visual jump between this and the rest of the app.
 */
import { BppisLogo } from "@/components/auth/bppis_logo";

export default function Loading() {
  return (
    <div className="flex min-h-screen flex-col items-center justify-center gap-4 bg-background px-6">
      <div className="w-24 shrink-0 sm:w-28">
        <BppisLogo priority />
      </div>
      <p className="text-center text-sm font-semibold tracking-wide text-foreground">
        Border Patrol Personnel Intelligence System
      </p>
      <span
        className="h-8 w-8 animate-spin rounded-full border-2 border-border border-t-accent"
        role="status"
        aria-label="Loading"
      />
    </div>
  );
}
